### ISSUE TITLE
fill tables with old data

### ISSUE THREAD

**Issue by runa** [jroakes/gsc-logger#10]
Hi! I was wondering if you have a recipe for filling the tables with data older than OFFSET_DAYS; I would love to fill the tables before the data is purged from search console.

Alternatively, we could modify the [cron action](https://github.com/jroakes/gsc-logger/blob/master/appengine/controllers/cron.py#L10) to accept a `offset_days` parameter to override the configuration, so this can be called with a script for the initial setup, like:

`curl http://blah.appspot.com/cron/?offset_days=[2-90]`

What do you think?

Thanks for GSC-Logger :)

**Comment by TKorr** [comment]
...I certainly would like welcome the ability to backfill the data
